# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('football', '0002_guess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
            ],
        ),
    ]
