# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guesses', to='football.Game'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
