# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20160508_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
