# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_guess_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guess',
            old_name='relust2',
            new_name='result2',
        ),
    ]
