# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20160508_1233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together=set([('user', 'game')]),
        ),
    ]
