# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20160529_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['full_name']},
        ),
    ]
